#!/usr/bin/env perl
use warnings;
use strict;
use open qw(locale);

#------------------------------------------------------------------------------
while (<>) {
    while (m{\#(?:[[:xdigit:]]{12}|[[:xdigit:]]{6}|[[:xdigit:]]{3})}g) {
        print("$&\n");
    }
}
