#!/usr/bin/env perl
use warnings;
use strict;

#------------------------------------------------------------------------------
use open IO => qw(:locale);
use Encode::Locale;
use Encode qw(decode);
BEGIN {
    @ARGV = map { decode('locale', $_, Encode::FB_CROAK) } @ARGV;
}

#------------------------------------------------------------------------------
while (<>) {
    while (m{\#(?:[[:xdigit:]]{12}|[[:xdigit:]]{6}|[[:xdigit:]]{3})}g) {
        print("$&\n");
    }
}
