#!/usr/bin/env perl
use warnings;
use strict;
use feature qw(say);

#------------------------------------------------------------------------------
use File::Basename qw(basename);
our $PROGNAME = basename($0);

#------------------------------------------------------------------------------
use open IO => qw(:locale);
use Encode::Locale;
use Encode qw(decode);
BEGIN {
    @ARGV = map { decode('locale', $_, Encode::FB_CROAK) } @ARGV;
}

###############################################################################

if (scalar @ARGV < 2) {
    die("not enough arguments\n");
}

my $regexp = shift(@ARGV);
my $extract = shift(@ARGV);

$regexp = qr{$regexp};

my $oldARGV;
while (<>) {
    if (!defined $oldARGV || $oldARGV ne $ARGV) {
        $. = 1;
        $oldARGV = $ARGV;
    }
    s{\R\z}{};
    if ($_ =~ $regexp) {
        my $expr = '"' . $extract . '"';
        my $extracted = eval $expr;
        if ($@) {
            warn($@);
            next;
        }
        print "$ARGV\t";
        print "$.\t";
        say $extracted;
    }
}
